"""Tests for library_indexer.build_library_index.

We exercise the indexer against a fake library directory of three tiny mp4s
(generated by conftest.make_fake_video). The extractor is monkeypatched so
the test never actually decodes a video — and so we can count extractor
calls precisely.

Coverage:
  * index.json is written with the correct schema after a first build.
  * re-running with unchanged mtime+size calls the extractor ZERO times.
  * changing mtime (touch) DOES re-extract that clip.
  * corrupt cache file is recovered gracefully (treated as empty).
  * unreadable / zero-duration clips are skipped, not added to the cache.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from broll_intelligence import build_library_index
from broll_intelligence.config import Settings
from broll_intelligence.feature_vector import empty_feature_vector
from broll_intelligence.library_indexer import (
    INDEX_VERSION,
    VIDEO_EXTS,
    load_index,
    load_index_as_clips,
)


def _fake_extractor_factory(call_log: list[Path]):
    """Build an extractor that records every call and returns a deterministic
    FeatureVector (so cache contents are testable)."""

    def _extract(path: Path, settings: Settings):
        call_log.append(path)
        fv = empty_feature_vector(str(path), source="library")
        fv.subjects = ["fake-subject"]
        fv.category = "movie"
        fv.confidence = 0.5
        return fv

    return _extract


# ---------------------------------------------------------------------------
# First build
# ---------------------------------------------------------------------------


def test_first_build_writes_index_json(
    video_files: list[Path],
    index_settings: Settings,
):
    call_log: list[Path] = []
    report = build_library_index(index_settings, _extractor=_fake_extractor_factory(call_log))

    # All three clips indexed, all re-extracted on the first build.
    assert report.total == 3
    assert report.indexed == 3
    assert report.re_extracted == 3
    assert report.skipped == 0
    assert report.failed == 0
    assert len(call_log) == 3

    # Cache file exists + has the right top-level shape.
    cache_path = index_settings.index_path
    assert cache_path.exists()
    raw = json.loads(cache_path.read_text(encoding="utf-8"))
    assert raw["version"] == INDEX_VERSION
    assert isinstance(raw["clips"], dict)
    assert len(raw["clips"]) == 3

    # Each entry has mtime, size, features.
    for abs_path, entry in raw["clips"].items():
        assert isinstance(entry["mtime"], (int, float))
        assert isinstance(entry["size"], int)
        assert entry["mtime"] > 0
        assert entry["size"] > 0
        assert "features" in entry
        feats = entry["features"]
        assert feats["category"] == "movie"
        assert feats["subjects"] == ["fake-subject"]
        assert feats["confidence"] == 0.5
        assert Path(abs_path).resolve() == Path(entry["features"]["media_path"]).resolve() or \
               Path(abs_path).resolve() == Path(feats["media_path"]).resolve()


# ---------------------------------------------------------------------------
# Incremental: no changes → no extractor calls
# ---------------------------------------------------------------------------


def test_unchanged_files_do_not_call_extractor(
    video_files: list[Path],
    index_settings: Settings,
):
    # First build — populate the cache.
    first_log: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(first_log))
    assert len(first_log) == 3

    # Second build — extractor must NOT be called.
    second_log: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(second_log)
    )

    assert len(second_log) == 0, "extractor was called on an unchanged cache"
    assert report.indexed == 3
    assert report.re_extracted == 0
    assert report.total == 3


# ---------------------------------------------------------------------------
# Incremental: mtime change → re-extract
# ---------------------------------------------------------------------------


def test_mtime_change_re_extracts(
    video_files: list[Path],
    index_settings: Settings,
):
    first_log: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(first_log))
    assert len(first_log) == 3

    # Bump mtime on the first clip — only that file should re-extract.
    target = video_files[0]
    stat = target.stat()
    os.utime(target, (stat.st_atime, stat.st_mtime + 10))

    second_log: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(second_log)
    )

    assert len(second_log) == 1
    assert second_log[0].resolve() == target.resolve()
    assert report.re_extracted == 1
    assert report.indexed == 3  # all three still present in cache


def test_size_change_re_extracts(
    video_files: list[Path],
    index_settings: Settings,
):
    first_log: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(first_log))

    # Change file size WITHOUT changing mtime (same second on Windows + most
    # filesystems rounds mtime to whole seconds, so use os.utime to be safe).
    target = video_files[1]
    with target.open("ab") as fh:
        fh.write(b"\x00" * 256)
    stat = target.stat()
    os.utime(target, (stat.st_atime, stat.st_mtime + 1))

    second_log: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(second_log))

    assert len(second_log) == 1
    assert second_log[0].resolve() == target.resolve()


def test_force_re_extracts_everything(
    video_files: list[Path],
    index_settings: Settings,
):
    first_log: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(first_log))
    assert len(first_log) == 3

    second_log: list[Path] = []
    report = build_library_index(
        index_settings, force=True, _extractor=_fake_extractor_factory(second_log)
    )
    assert len(second_log) == 3
    assert report.re_extracted == 3


# ---------------------------------------------------------------------------
# Corrupt / missing cache → treat as empty
# ---------------------------------------------------------------------------


def test_corrupt_cache_is_treated_as_empty(
    video_files: list[Path],
    index_settings: Settings,
):
    index_settings.index_path.parent.mkdir(parents=True, exist_ok=True)
    index_settings.index_path.write_text("{ this is not json", encoding="utf-8")

    log: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(log)
    )

    # Cache was unreadable → treated as empty → all 3 files re-extracted.
    assert len(log) == 3
    assert report.indexed == 3
    # And a fresh, valid cache file should now exist.
    raw = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert raw["version"] == INDEX_VERSION
    assert len(raw["clips"]) == 3


def test_wrong_version_cache_is_treated_as_empty(
    video_files: list[Path],
    index_settings: Settings,
):
    index_settings.index_path.parent.mkdir(parents=True, exist_ok=True)
    index_settings.index_path.write_text(
        json.dumps({"version": 99, "clips": {}}),
        encoding="utf-8",
    )

    log: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(log)
    )
    assert report.indexed == 3
    assert len(log) == 3
    raw = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert raw["version"] == INDEX_VERSION


# ---------------------------------------------------------------------------
# Skip unreadable / zero-duration clips
# ---------------------------------------------------------------------------


def test_unreadable_clip_is_skipped(
    video_files: list[Path],
    index_settings: Settings,
    monkeypatch: pytest.MonkeyPatch,
):
    # Pretend one file has zero duration — probe_duration returns 0 → the
    # extractor returns an empty_feature_vector. The indexer must skip it
    # (not add it to the cache).
    from broll_intelligence import library_indexer

    def _fake_extract(path: Path, settings: Settings):
        if path.name == "clip_b.mp4":
            return empty_feature_vector(str(path), source="library")
        fv = empty_feature_vector(str(path), source="library")
        fv.subjects = ["x"]
        fv.category = "movie"
        fv.confidence = 0.5
        return fv

    report = build_library_index(index_settings, _extractor=_fake_extract)
    assert report.total == 3
    assert report.indexed == 2
    assert report.skipped == 1

    raw = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    cached_paths = [Path(p).name for p in raw["clips"]]
    assert "clip_b.mp4" not in cached_paths


def test_missing_library_dir_is_noop(
    index_settings: Settings,
):
    """If the configured library dir doesn't exist, the indexer returns an
    empty report rather than crashing."""
    # Override to a dir that doesn't exist.
    import shutil

    if index_settings.library_dir.exists():
        shutil.rmtree(index_settings.library_dir)
    assert not index_settings.library_dir.exists()

    log: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(log)
    )
    assert report.total == 0
    assert report.indexed == 0
    assert log == []
    # The cache file is still written (with empty clips) so downstream
    # consumers have something predictable to load.
    raw = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert raw["clips"] == {}


# ---------------------------------------------------------------------------
# Persistence is atomic
# ---------------------------------------------------------------------------


def test_persistence_writes_valid_json_atomically(
    video_files: list[Path],
    index_settings: Settings,
):
    build_library_index(index_settings, _extractor=_fake_extractor_factory([]))
    raw = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert raw["version"] == INDEX_VERSION
    assert "clips" in raw
    # No leftover .tmp files in the cache dir.
    tmp_files = list(index_settings.index_path.parent.glob(".broll_intelligence_index.*.tmp"))
    assert tmp_files == [], f"stale tmp files left behind: {tmp_files}"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------


def test_load_index_returns_empty_when_no_cache(
    tmp_path: Path,
):
    from broll_intelligence.config import Settings

    settings = Settings(
        library_dir=tmp_path / "library",
        index_path=tmp_path / "missing.json",
        data_dir=tmp_path,
    )
    assert load_index(settings) == {}


def test_load_index_as_clips_returns_typed_clips(
    video_files: list[Path],
    index_settings: Settings,
):
    build_library_index(index_settings, _extractor=_fake_extractor_factory([]))
    clips = load_index_as_clips(index_settings)
    assert len(clips) == 3
    for c in clips:
        assert c.path.exists()
        assert c.mtime > 0
        assert c.size > 0
        assert c.features.category == "movie"


# ---------------------------------------------------------------------------
# VIDEO_EXTS constant
# ---------------------------------------------------------------------------


def test_video_exts_matches_app_broll():
    """Same extension set as app/broll.py — otherwise the two indexes
    disagree about what counts as a B-roll file."""
    assert VIDEO_EXTS == frozenset({".mp4", ".mov", ".mkv", ".webm", ".m4v"})


# ---------------------------------------------------------------------------
# New file appearing in the library
# ---------------------------------------------------------------------------


def test_new_file_is_extracted(
    video_files: list[Path],
    index_settings: Settings,
):
    # First build with 3 files.
    log1: list[Path] = []
    build_library_index(index_settings, _extractor=_fake_extractor_factory(log1))
    assert {p.resolve() for p in log1} == {p.resolve() for p in video_files}

    # Add a new clip.
    new_clip = video_files[0].parent / "clip_d.mp4"
    new_clip.write_bytes(b"\x00" * 4096)

    # Re-build — only the new file should be extracted.
    log2: list[Path] = []
    report = build_library_index(
        index_settings, _extractor=_fake_extractor_factory(log2)
    )
    assert len(log2) == 1
    assert log2[0].resolve() == new_clip.resolve()
    assert report.indexed == 4
    assert report.re_extracted == 1


# ---------------------------------------------------------------------------
# Removed file is dropped from the cache (next rebuild sees it missing)
# ---------------------------------------------------------------------------


def test_removed_file_drops_from_cache_on_next_build(
    video_files: list[Path],
    index_settings: Settings,
):
    build_library_index(index_settings, _extractor=_fake_extractor_factory([]))
    raw_before = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert len(raw_before["clips"]) == 3

    video_files[0].unlink()

    build_library_index(index_settings, _extractor=_fake_extractor_factory([]))
    raw_after = json.loads(index_settings.index_path.read_text(encoding="utf-8"))
    assert len(raw_after["clips"]) == 2
    remaining = {Path(p).name for p in raw_after["clips"]}
    assert "clip_a.mp4" not in remaining